name: skylashes
favicon: null
layout_spectrum: 0.28553
typography_spectrum: 0.56346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#472a6d'
    - '#bbbcaa'
    - '#7f8c46'
  brandStrength: 0
  lightness: 0.005997301312163472
  saturation: 0.34033255954273045
  rhythmicContrast: 0.18818618636578321
purpose: []
