name: skylashes
favicon: null
layout_spectrum: 0.34543
typography_spectrum: 0.8555712099187076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7987701341044158
  lightness: 0.005997301312163472
  saturation: 0.34033255954273045
  rhythmicContrast: 0.18818618636578321
purpose: []
